# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_cleaning_functions.ipynb.

# %% auto #0
__all__ = ['STOPS_TRACKED_COLS', 'STOPS_SILVER_COLS', 'explode_stop_groups', 'deduplicate_stops', 'compute_row_hash',
           'prepare_stops_staging', 'ensure_silver_stops_table', 'find_stops_to_expire', 'build_new_stop_records',
           'apply_stops_scd2']

# %% ../03_cleaning_functions.ipynb #0ff19a06
from pyspark.sql.window import Window
from pyspark.sql import SparkSession, DataFrame, functions as F
from delta.tables import DeltaTable
from datetime import datetime, UTC

# %% ../03_cleaning_functions.ipynb #30cc6de8
def explode_stop_groups(bronze_stops_df: DataFrame) -> DataFrame:
    """Flatten stopGroups array into one row per stop-group with source_timestamp."""
    return (
        bronze_stops_df
        .select(
            F.explode("stopGroups").alias("sg"),
            F.to_timestamp("generatedAt").alias("source_timestamp"),
        )
        .select("sg.*", "source_timestamp")
    )

# %% ../03_cleaning_functions.ipynb #371bb9b0
def deduplicate_stops(stops_df: DataFrame) -> DataFrame:
    """Keep only the latest row per (node, cis) based on source_timestamp."""
    w = Window.partitionBy("node", "cis").orderBy(F.col("source_timestamp").desc())
    return stops_df.withColumn("_rn", F.row_number().over(w)).filter("_rn = 1").drop("_rn")

# %% ../03_cleaning_functions.ipynb #e13ec466
# Tracked attribute columns for change-detection hash
STOPS_TRACKED_COLS = [
    "name", "fullName", "uniqueName", "municipality", "districtCode",
    "avgLat", "avgLon", "avgJtskX", "avgJtskY",
    "isTrain", "mainTrafficType", "idosCategory", "idosName", "stops",
]


def compute_row_hash(df: DataFrame, cols: list[str] = STOPS_TRACKED_COLS) -> DataFrame:
    """Add MD5 hash over tracked attributes for change detection."""
    return df.withColumn(
        "row_hash",
        F.md5(F.concat_ws("||", *[F.to_json(F.struct(F.col(c))) for c in cols])),
    )

# %% ../03_cleaning_functions.ipynb #56351276
def prepare_stops_staging(bronze_stops_df: DataFrame) -> DataFrame:
    """Compose: explode → deduplicate → add row hash."""
    return compute_row_hash(deduplicate_stops(explode_stop_groups(bronze_stops_df)))

# %% ../03_cleaning_functions.ipynb #ad51871c
def ensure_silver_stops_table(spark: SparkSession, silver_stops_table: str) -> None:
    """Create the silver SCD2 stops table if it does not already exist."""
    spark.sql(
        """
        CREATE TABLE IF NOT EXISTS IDENTIFIER(:silver_stops_table) (
          node BIGINT,
          cis BIGINT,
          name STRING,
          fullName STRING,
          uniqueName STRING,
          municipality STRING,
          districtCode STRING,
          avgLat DOUBLE,
          avgLon DOUBLE,
          avgJtskX DOUBLE,
          avgJtskY DOUBLE,
          isTrain BOOLEAN,
          mainTrafficType STRING,
          idosCategory BIGINT,
          idosName STRING,
          stops ARRAY<STRUCT<
            altIdosName: STRING,
            gtfsIds: ARRAY<STRING>,
            id: STRING,
            isMetro: BOOLEAN,
            jtskX: DOUBLE,
            jtskY: DOUBLE,
            lat: DOUBLE,
            lines: ARRAY<STRUCT<
              direction: STRING,
              direction2: STRING,
              exitOnly: BOOLEAN,
              id: BIGINT,
              isNight: BOOLEAN,
              name: STRING,
              type: STRING
            >>,
            lon: DOUBLE,
            mainTrafficType: STRING,
            platform: STRING,
            wheelchairAccess: STRING,
            zone: STRING
          >>,
          row_hash STRING,
          valid_from TIMESTAMP,
          valid_to TIMESTAMP,
          is_current BOOLEAN
        )
        """,
        args={"silver_stops_table": silver_stops_table},
    )

# %% ../03_cleaning_functions.ipynb #f3e250b5
STOPS_SILVER_COLS = [
    "node", "cis", "name", "fullName", "uniqueName",
    "municipality", "districtCode",
    "avgLat", "avgLon", "avgJtskX", "avgJtskY",
    "isTrain", "mainTrafficType", "idosCategory", "idosName",
    "stops", "row_hash",
]


def find_stops_to_expire(staging_stops_df: DataFrame, silver_stops_df: DataFrame) -> DataFrame:
    """Return staging rows whose hash differs from the current silver version."""
    current = silver_stops_df.filter("is_current").select("node", "cis", "row_hash")
    return (
        staging_stops_df.alias("s")
        .join(current.alias("t"), ["node", "cis"])
        .filter("s.row_hash != t.row_hash")
        .select("s.*")
    )

# %% ../03_cleaning_functions.ipynb #88ba3739
def build_new_stop_records(staging_stops_df: DataFrame, silver_stops_df: DataFrame) -> DataFrame:
    """Build rows to insert: genuinely new keys + just-expired changed keys."""
    current_keys = silver_stops_df.filter("is_current").select("node", "cis")
    return (
        staging_stops_df.alias("s")
        .join(current_keys.alias("t"), ["node", "cis"], "left_anti")
        .select(
            *STOPS_SILVER_COLS,
            F.col("source_timestamp").alias("valid_from"),
            F.lit(None).cast("timestamp").alias("valid_to"),
            F.lit(True).alias("is_current"),
        )
    )

# %% ../03_cleaning_functions.ipynb #b865bff9
def apply_stops_scd2(spark: SparkSession, bronze_stops_table: str, silver_stops_table: str) -> tuple[int, int]:
    """Run the full SCD2 merge: prepare staging from bronze, expire changed rows, insert new + changed."""
    staging_stops_df = prepare_stops_staging(spark.table(bronze_stops_table))
    silver = DeltaTable.forName(spark, silver_stops_table)
    now = datetime.now(UTC)

    # Step 1: Expire changed records
    to_expire = find_stops_to_expire(staging_stops_df, silver.toDF())
    expired_count = to_expire.count()

    if expired_count > 0:
        silver.alias("t").merge(
            to_expire.alias("s"),
            "t.node = s.node AND t.cis = s.cis AND t.is_current = TRUE",
        ).whenMatchedUpdate(set={
            "is_current": F.lit(False),
            "valid_to": F.lit(now),
        }).execute()

    # Step 2: Insert new + changed records (reads silver AFTER expire)
    new_records = build_new_stop_records(staging_stops_df, silver.toDF())
    inserted_count = new_records.count()

    if inserted_count > 0:
        new_records.write.mode("append").saveAsTable(silver_stops_table)

    return expired_count, inserted_count
