# AUTOGENERATED! DO NOT EDIT! File to edit: ../02_fetching_functions.ipynb.

# %% auto #0
__all__ = ['fetch_pid_stops', 'get_stops_file_name']

# %% ../02_fetching_functions.ipynb #3fc5f5c2
import requests
import time

# %% ../02_fetching_functions.ipynb #b4ec8939
def fetch_pid_stops() -> bytes:
    """Fetch PID stops data from the API and return raw response content.
    
    Raises:
        requests.HTTPError: If the API returns a non-2xx status.
    """
    PID_STOPS_URL = "http://data.pid.cz/stops/json/stops.json"
    response = requests.get(PID_STOPS_URL, timeout=30)
    response.raise_for_status()
    return response.content

# %% ../02_fetching_functions.ipynb #57ec39fd
def get_stops_file_name() -> str:
    """Generate a unique file name for stops data using the current unix timestamp.

    Returns:
        A string in the format `<unix_timestamp>.json`.
    """
    unix_timestamp = int(time.time())
    return f"{unix_timestamp}.json"
